
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG
    reactor:
      netty:
        http:
          client: DEBUG

spring:
  application:
    name: api-gateway
  cloud:
    discovery:
      enabled: 'true'
    gateway:
      server:
        webflux:
          globalcors:
            add-to-simple-url-handler-mapping: true
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - http://localhost:5173
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - PATCH
                  - DELETE
                  - OPTIONS
                allowedHeaders:
                  - '*'
                exposedHeaders:
                  - Authorization
                allowCredentials: true
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
          routes:
          - id: order-service
            uri: lb://order-service
            predicates:
              - Path=/api/orders/**
            filters:
              - name: CircuitBreaker
                args:
                  name: order
                  fallbackUri: forward:/fallbacks/order

          - id: product-service
            uri: lb://product-service
            predicates:
              - Path=/api/products,/api/products/**,/api/categories,/api/categories/**,/api/brands,/api/brands/**
            filters:
              - name: CircuitBreaker
                args:
                  name: product
                  fallbackUri: forward:/fallbacks/product


          - id: upload-service
            uri: lb://upload-service
            predicates:
              - Path=/api/uploads,/api/uploads/**
            filters:
              - name: CircuitBreaker
                args:
                  name: upload
                  fallbackUri: forward:/fallbacks/upload
          - id: auth-service
            uri: lb://auth-service
            predicates:
              - Path=/api/auth/**
            filters:
              - name: CircuitBreaker
                args:
                  name: auth
                  fallbackUri: forward:/fallbacks/auth

          - id: user-service
            uri: lb://user-service
            predicates:
              - Path=/api/users/**
            filters:
              - name: CircuitBreaker
                args:
                  name: user
                  fallbackUri: forward:/fallbacks/user

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    circuitbreakers:
      enabled: 'true'
  endpoint:
    health:
      show-details: always

resilience4j.circuitbreaker:
    instances:
      product:
        registerHealthIndicator: true
        event-consumer-buffer-size: 10
        slidingWindowSize: 5
        slidingWindowType: COUNT_BASED
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

      upload:
        registerHealthIndicator: true
        event-consumer-buffer-size: 10
        slidingWindowSize: 5
        slidingWindowType: COUNT_BASED
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

      order:
        registerHealthIndicator: true
        event-consumer-buffer-size: 10
        slidingWindowSize: 5
        slidingWindowType: COUNT_BASED
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
      auth:
        registerHealthIndicator: true
        event-consumer-buffer-size: 10
        slidingWindowSize: 5
        slidingWindowType: COUNT_BASED
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
      user:
        registerHealthIndicator: true
        event-consumer-buffer-size: 10
        slidingWindowSize: 5
        slidingWindowType: COUNT_BASED
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

resilience4j.timelimiter:
    instances:
      upload:
        timeoutDuration: 30s
        cancelRunningFuture: false
