spring.application.name=article-service
server.port=4048
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/article_service_db
spring.datasource.username=postgres
spring.datasource.password=sapassword
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

